### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by jeffteixeira** [flathub/com.visualstudio.code.tool.fish#1]
I tried to configure the fish by creating the ~/.config/fish/config.fish file, but apparently that file was not loaded. Which path should the shell configuration be on?

**Comment by gasinvein** [comment]
fish respects `$XDG_CONFIG_HOME`, which should be set to `~/.var/app/com.visualstudio.code/config` in the VSCode flatpak sandbox.

**Comment by jeffteixeira** [comment]
Thank you very much. Now I managed to make it work. To make the fish the default shell, just override the SHELL variable?

**Comment by gasinvein** [comment]
I think changing settings built-in terminal in VSCode would be more appropriate. You can select which shell to spawn there.

**Comment by jeffteixeira** [comment]
Ok, thanks for the clarifications! :)
