### ISSUE TITLE
Add 23.08 branch

### ISSUE THREAD

**Issue by awebeer256** [flathub/com.visualstudio.code.tool.fish#16]
VSCodium now depends on `org.freedesktop.Sdk//23.08`, so `com.visualstudio.code.tool.fish//22.08` no longer works with it. We need to add a `//23.08` branch. See also [here](https://github.com/flathub/com.vscodium.codium/issues/37#issuecomment-1512316459).

**Comment by awebeer256** [comment]
Having never packaged anything as a flatpak before, it looks like the fix might literally be just a find-replace 22.08 -> 23.08 in the yml file?

**Comment by rowbawts** [comment]
I'd also like to see this be updated to 23.08 for use with VSCodium.

**Comment by VinnieSift** [comment]
Now Visual Studio Code also depends on 23.08 and both fish and podman stopped working too

**Comment by dynnian** [comment]
Why hasn't this been done yet? This package is now basically useless unless it's updated to 23.08

**Comment by bbhtt** [comment]
Done via https://github.com/flathub/com.visualstudio.code.tool.fish/commit/f005dac6adf407c374c1a20e74a65ec558db71d7
